/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IStargateQuery } from "./IStargateQuery";
export type { IStargateSwapper } from "./IStargateSwapper";
