/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as gmx from "./gmx";
export type { gmx };
export type { IFeeCollector } from "./IFeeCollector";
export type { IWETHToken } from "./IWETHToken";
