/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IConvexBooster } from "./IConvexBooster";
export type { IConvexRewardPool } from "./IConvexRewardPool";
export type { IConvexZap } from "./IConvexZap";
