/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IGmxVault,
  IGmxVaultInterface,
} from "../../../../contracts/interfaces/gmx/IGmxVault";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_token",
        type: "address",
      },
    ],
    name: "getMaxPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_token",
        type: "address",
      },
    ],
    name: "getMinPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IGmxVault__factory {
  static readonly abi = _abi;
  static createInterface(): IGmxVaultInterface {
    return new utils.Interface(_abi) as IGmxVaultInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IGmxVault {
    return new Contract(address, _abi, signerOrProvider) as IGmxVault;
  }
}
