/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CTokenMock } from "./CTokenMock";
export type { CompoundStrategy } from "./CompoundStrategy";
export type { ICToken } from "./ICToken";
