/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as uniswapv2 from "./uniswapv2";
export type { uniswapv2 };
export type { ERC20Mock } from "./ERC20Mock";
